[package]
name = "rustberry"
version = "0.1.0"
authors = ["Petr Hodina <hodinapetr46@gmail.com>"]

[lib]
name = "rustberry"
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
